Add godocs, comments and README contents
system-transparency/stmgr pull request #16
Opened 2022-02-04 10:53 UTC by MDr164

Signed-off-by: Marvin Drees <marvin.drees@9elements.com>

2022-02-07 17:35 UTC, sylv-io requested changes

2022-02-07 17:35 UTC, sylv-io commented on README.md
> +Either run `go install github.com/system/transparency` or clone the repo and run `go build`.
`go install github.com/system-transparency/stmgr@latest`

2022-02-08 10:03 UTC, sylv-io requested changes

2022-02-08 10:03 UTC, sylv-io commented on README.md
> +## Installtion instructions
Installation

2022-02-08 10:03 UTC, sylv-io commented on README.md
> +This tool requires to be invoked with a command and corresponding subcommand.
invocation

2022-02-08 10:03 UTC, sylv-io commented on README.md
> +In that example `ospkg` is the command and `create` is the subcommand.
In that example, `ospkg` ...

2022-02-08 10:03 UTC, sylv-io commented on eval/keygen.go
> +// package. It the calls keygen.Certificate after they are parsed.
It then calls keygen. Certificate after they are parsed.
-------^------------------^

2022-02-08 10:03 UTC, sylv-io commented on eval/ospkg.go
> +// package. It the calls ospkg.Create after they are parsed.
It then calls ospkg. Create after they are parsed.
-------^----------------^

2022-02-08 10:03 UTC, sylv-io commented on eval/ospkg.go
> +// package. It the calls ospkg.Sign after they are parsed.
same here

2022-02-08 10:03 UTC, sylv-io commented on eval/provision.go
> +// package. It the calls provision.Cfgtool after they are parsed.
same here

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +		// Create a selfsigned certificate.
self-signed

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +// This function makes sure the ondisk format of the key and certificate are correct.
on-disk

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +// This is the core function to create certificate and the corresponding ed25519 key.
a certificate ?
not sure

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +// It uses golangs std crypto package and uses a cryptographcially secure (enough) source
Golangs

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +// It uses golangs std crypto package and uses a cryptographcially secure (enough) source
cryptographically

2022-02-08 10:03 UTC, sylv-io commented on keygen/certificate.go
> +// It uses golangs std crypto package and uses a cryptographcially secure (enough) source
of entropy, namely

2022-02-08 10:03 UTC, sylv-io commented on keygen/util.go
> +// and returns a pointer of the pem.Block data.
a pointer to the ..

2022-02-08 10:03 UTC, sylv-io commented on ospkg/create.go
> +// stboot/ospkg package. If no errors occur it will
occur, it

2022-02-08 10:03 UTC, sylv-io commented on provision/cfgtool.go
> +// host configuration json file. If any value of the host
JSON

2022-02-08 10:03 UTC, sylv-io commented on provision/parser.go
> +// looks like but does not implement their custom types and
, but

2022-02-08 10:03 UTC, sylv-io commented on provision/parser.go
> +// looks like but does not implement their custom types and
, but

2022-02-08 10:03 UTC, sylv-io commented on provision/tui.go
> +// It uses tview for that as it abstracts tcell functions and makes building
that, as

2022-02-08 10:03 UTC, sylv-io commented on provision/tui.go
> +// a few linter breaking code idioms which you can find in as nolint stanzas.
idioms, which

2022-02-08 10:06 UTC, MDr164 commented on README.md
> +## Installtion instructions
Ack

2022-02-08 10:06 UTC, MDr164 commented on README.md
> +This tool requires to be invoked with a command and corresponding subcommand.
I don't think this word makes any sense in this sentence. Mind telling me where you wanted to put it?

2022-02-08 10:07 UTC, MDr164 commented on README.md
> +In that example `ospkg` is the command and `create` is the subcommand.
Ack

2022-02-08 10:07 UTC, MDr164 commented on eval/keygen.go
> +// package. It the calls keygen.Certificate after they are parsed.
There is deliberately no space after the dot, as this is a function name and not a sentence end. The missing n is indeed missing though.

2022-02-08 10:08 UTC, MDr164 commented on eval/ospkg.go
> +// package. It the calls ospkg.Create after they are parsed.
See above

2022-02-08 10:08 UTC, MDr164 commented on eval/ospkg.go
> +// package. It the calls ospkg.Sign after they are parsed.
See above

2022-02-08 10:08 UTC, MDr164 commented on eval/provision.go
> +// package. It the calls provision.Cfgtool after they are parsed.
See above

2022-02-08 10:08 UTC, MDr164 commented on keygen/certificate.go
> +		// Create a selfsigned certificate.
Ack

2022-02-08 10:08 UTC, MDr164 commented on keygen/certificate.go
> +// This function makes sure the ondisk format of the key and certificate are correct.
Ack

2022-02-08 10:09 UTC, MDr164 commented on keygen/certificate.go
> +// This is the core function to create certificate and the corresponding ed25519 key.
Ack

2022-02-08 10:09 UTC, MDr164 commented on keygen/certificate.go
> +// It uses golangs std crypto package and uses a cryptographcially secure (enough) source
Ack

2022-02-08 10:09 UTC, MDr164 commented on keygen/util.go
> +// and returns a pointer of the pem.Block data.
Ack

2022-02-08 10:10 UTC, MDr164 commented on ospkg/create.go
> +// stboot/ospkg package. If no errors occur it will
Ack

2022-02-08 10:10 UTC, MDr164 commented on provision/cfgtool.go
> +// host configuration json file. If any value of the host
Ack

2022-02-08 10:10 UTC, sylv-io commented on README.md
> +This tool requires to be invoked with a command and corresponding subcommand.
Indeed, sorry :D

2022-02-08 10:10 UTC, MDr164 commented on provision/parser.go
> +// looks like but does not implement their custom types and
Ack

2022-02-08 10:10 UTC, MDr164 commented on provision/tui.go
> +// a few linter breaking code idioms which you can find in as nolint stanzas.
Ack

2022-02-08 10:10 UTC, MDr164 commented on provision/tui.go
> +// It uses tview for that as it abstracts tcell functions and makes building
Ack

2022-02-08 12:10 UTC, sylv-io approved these changes

2022-02-08 12:28 UTC, merged