Add shortcuts, test stubs and change flag error behaviour
system-transparency/stmgr pull request #6
Opened 2022-01-18 10:40 UTC by MDr164

This commit is just minor cleanup. The test stubs are just
dummy files that add reminders to add tests. In addition
the flags are now extended with shortcuts.

Signed-off-by: Marvin Drees <marvin.drees@9elements.com>

2022-01-18 13:13 UTC, MDr164 commented
It was proposed to restructure the commands and its subcommands so the shortcuts will likely go away.

2022-01-19 12:00 UTC, sylv-io requested changes

2022-01-19 12:00 UTC, sylv-io commented on stmgr.go
> +	Not yet implemented!
remove trailing whitespace

2022-01-19 12:00 UTC, sylv-io commented on stmgr.go
> +	build:
Should we remove all "not implemented" commands for now?

2022-01-19 12:00 UTC, sylv-io commented on stmgr.go
> +		Not yet implemented!
same here

2022-01-19 12:00 UTC, sylv-io commented on stmgr.go
> +	Not yet implemented!
or remove it, too :monkey:

2022-01-19 12:00 UTC, sylv-io commented on stmgr.go
> +Use 'stmgr keygen <SUBCOMMAND> -help' for more info.
no help for keygen <subcommand>

2022-01-19 12:02 UTC, MDr164 commented on stmgr.go
> +Use 'stmgr keygen <SUBCOMMAND> -help' for more info.
Fixed

2022-01-19 13:40 UTC, MDr164 commented on stmgr.go
> +		Not yet implemented!
I removed the reference in the usage text but kept the code for them. They'll be implemented soon anyways.

2022-01-19 14:30 UTC, sylv-io approved these changes

2022-01-19 14:31 UTC, merged